spring.application.name=ecommerce-backend

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/api/v1

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

media.locationProduct=
media.location=


#spring.data.web.pageable.default-page-size=10
#spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.one-indexed-parameters=true


security.jwt.expiration-in-minutes=30
security.jwt.secret-key=
security.default.role=CLIENTE


mercadopago.access.token=TEST-5900423857385466-090917-d060d87b4349fcdb509a10b96774071b-1094656107


# Logs detallados para debug
logging.level.tu.paquete.WebhookDebugController=DEBUG
logging.level.com.mercadopago=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

activation.account.token.expiration-hours: 24
app.frontend.url:

#Correo
# Configuración del servidor SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=

# Propiedades adicionales de seguridad y autenticación
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


